/**
 * Infer aircraft registration state from ICAO 24-bit Mode S address (6 hex chars).
 * Uses the first 2 hex digits against common allocation blocks (approximate).
 */

const HEX2_UNIQUE: Record<string, string> = {
  // United States (incl. common military AE/AF blocks)
  A0: "United States",
  A1: "United States",
  A2: "United States",
  A3: "United States",
  A4: "United States",
  A5: "United States",
  A6: "United States",
  A7: "United States",
  A8: "United States",
  A9: "United States",
  AA: "United States",
  AB: "United States",
  AC: "United States",
  AD: "United States",
  AE: "United States",
  AF: "United States",
  // Canada
  C0: "Canada",
  C1: "Canada",
  C2: "Canada",
  C3: "Canada",
  C4: "Canada",
  C5: "Canada",
  C6: "Canada",
  C7: "Canada",
  C8: "Canada",
  C9: "Canada",
  CA: "Canada",
  CB: "Canada",
  CC: "Canada",
  CD: "Canada",
  CE: "Canada",
  CF: "Canada",
  // UK
  "40": "United Kingdom",
  "41": "United Kingdom",
  "42": "United Kingdom",
  "43": "United Kingdom",
  "44": "United Kingdom",
  "45": "United Kingdom",
  // France
  "39": "France",
  "3A": "France",
  "3B": "France",
  // Germany / Austria / CH overlap — coarse
  "3C": "Germany",
  "3D": "Germany",
  "3E": "Germany",
  "3F": "Germany",
  "4C": "Switzerland",
  "4D": "Switzerland",
  // Spain
  "34": "Spain",
  "35": "Spain",
  // Italy
  "30": "Italy",
  "31": "Italy",
  "32": "Italy",
  "33": "Italy",
  // Nordics
  "47": "Norway",
  "4A": "Sweden",
  "4B": "Sweden",
  "14": "Finland",
  "15": "Finland",
  // Benelux
  "48": "Netherlands",
  "49": "Netherlands",
  "50": "Netherlands",
  "51": "Netherlands",
  "52": "Netherlands",
  "53": "Netherlands",
  "54": "Netherlands",
  "55": "Netherlands",
  "56": "Netherlands",
  "57": "Netherlands",
  // Eastern EU
  "5A": "Czech Republic",
  "5B": "Slovakia",
  "1E": "Poland",
  "1F": "Poland",
  // Russia / CIS (coarse)
  "23": "Russia",
  "24": "Russia",
  "25": "Russia",
  "26": "Russia",
  "27": "Russia",
  "28": "Russia",
  "29": "Russia",
  "2A": "Russia",
  "2B": "Russia",
  "2C": "Russia",
  "2D": "Russia",
  "2E": "Russia",
  "2F": "Russia",
  // Middle East
  "0A": "United Arab Emirates",
  "0B": "Israel",
  "0C": "India",
  "0D": "Saudi Arabia",
  "0E": "Kuwait",
  "0F": "Qatar",
  "90": "Turkey",
  "91": "Israel",
  // South / Southeast Asia
  "92": "India",
  "93": "Pakistan",
  "94": "Afghanistan",
  "95": "Sri Lanka",
  "96": "Myanmar",
  "97": "Indonesia",
  "98": "Indonesia",
  "99": "Indonesia",
  // East Asia
  "80": "Japan",
  "81": "Japan",
  "82": "Japan",
  "83": "Japan",
  "84": "South Korea",
  "85": "South Korea",
  "86": "Vietnam",
  "87": "Thailand",
  "88": "China",
  "89": "China",
  "8A": "China",
  "8B": "China",
  "8C": "China",
  "8D": "China",
  "8E": "China",
  "8F": "China",
  // Australia / NZ
  "70": "Australia",
  "71": "Australia",
  "72": "Australia",
  "73": "Australia",
  "74": "Australia",
  "75": "Australia",
  "76": "Australia",
  "77": "Australia",
  "78": "Australia",
  "79": "Australia",
  "7A": "Australia",
  "7B": "Australia",
  "7C": "Australia",
  "60": "New Zealand",
  "61": "New Zealand",
  "62": "New Zealand",
  "63": "New Zealand",
  "64": "New Zealand",
  "65": "New Zealand",
  "66": "New Zealand",
  "67": "New Zealand",
  "68": "New Zealand",
  "69": "New Zealand",
  "6A": "New Zealand",
  "6B": "New Zealand",
  "6C": "New Zealand",
  "6D": "New Zealand",
  "6E": "New Zealand",
  "6F": "New Zealand",
  // Southern Americas
  E0: "Argentina",
  E1: "Brazil",
  E2: "Chile",
  E3: "Colombia",
  E4: "Mexico",
  E5: "Venezuela",
  // Small EU
  "10": "Belgium",
  "11": "Belgium",
  "12": "Belgium",
  "13": "Belgium",
  "16": "Greece",
  "17": "Hungary",
  "18": "Ireland",
  "19": "Iceland",
  "1A": "Liechtenstein",
  "1B": "Luxembourg",
  "1C": "Malta",
  "1D": "Monaco",
  "20": "Portugal",
  "21": "Portugal",
  "22": "Romania",
};

export function countryFromIcao24Hex(hex: string | undefined | null): string | undefined {
  if (!hex) return undefined;
  const h = hex.replace(/^0x/i, "").toUpperCase().replace(/[^0-9A-F]/g, "");
  if (h.length < 2) return undefined;
  const padded = h.padStart(6, "0").slice(0, 6);
  const key2 = padded.slice(0, 2);
  return HEX2_UNIQUE[key2];
}
